language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: nightly
    - php: hhvm

before_script:
  - composer install --prefer-source --dev

script:
  - php vendor/bin/phpunit

notifications:
  email:
    on_success: change
    on_failure: change
