language: php

php:
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer install --prefer-source --ignore-platform-reqs

script:
  - php vendor/bin/phpunit

notifications:
  email:
    on_success: change
    on_failure: change
