language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: nightly
    - php: hhvm

before_script:
  - composer install --prefer-source --dev

script:
  - php vendor/bin/phpunit

notifications:
  email:
    on_success: change
    on_failure: change
